<h2>lasVegas.csv Business Processing

<h4>Import Statements

In [1]:
import pandas as pd
import json
import numpy as np
import ast
from tqdm import tqdm_notebook

<h4>Reading lasVegas.csv into Pandas Dataframe df

In [2]:
df=pd.DataFrame.from_csv('/home/rim/Desktop/Yelp dataset/lasVegas.csv')
df.shape

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


(28853, 15)

In [3]:
#Reading from yelp json
#df=pd.read_json('/home/rim/Desktop/Yelp dataset/yelp_academic_dataset_business.json',lines=True)
#df.shape

In [4]:
#df.columns.values
#df.loc[df['state'] == 'CA']

<h4>Select required columns and rename columns to standard names

In [5]:
df=df[['business_id','name','neighborhood','address','city','state','postal_code','stars','review_count','attributes']]
df.columns=['BusinessId',"RestaurantName",'Neighborhood',"Address",'City','State','Zip','Stars','ReviewCount','attributes']
df.columns.values

array(['BusinessId', 'RestaurantName', 'Neighborhood', 'Address', 'City',
       'State', 'Zip', 'Stars', 'ReviewCount', 'attributes'], dtype=object)

<h4>Divide df into 2 parts - attributes and the rest

In [6]:
df_1=df[['BusinessId',"RestaurantName",'Neighborhood',"Address",'City','State','Zip','Stars','ReviewCount']]
df_2=df[['attributes']]

<h4> Replace blank with ''

In [7]:
df_1.fillna('', inplace=True)
df_1

/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py:3790: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)


BusinessId                            RestaurantName  \
17      hTzcHtk4-0QJnFUbkKpd5Q                               Citi Trends   
18      UwIpS9UKsPiKAv1fiEYhqg             Nevada Title And Payday Loans   
19      vJIuDBdu01vCA8y1fwR1OQ                                CakesbyToi   
20      YZCHr68c5aEVHz0bkq9K2g                         Park Stone Pavers   
32      kgffcoxT6BQp-gJ-UQ7Czw                                    Subway   
33      0jtRI7hVMpQHpUVtUy4ITw                    Omelet House Summerlin   
44      0i6GlR5YTCMlwthjqw6ZTQ                    Cinthya's Beauty Salon   
45      oSS0p8TeF9BTTD7QWtO6gg                           Aria Remodeling   
50      DR30lzIHVTF6xhyMI-3IlQ                    Not Just Antiques Mart   
52      VVtPNiqwtR_Os7J51mANGQ           JAM Scooter Rental Of Las Vegas   
58      syCI-5YJ8VJhFzHlzfpP0g                          Shower Solutions   
61      JJEx5wIqs9iGGATOagE8Sg                  Baja Fresh Mexican Grill   
65      JbIi9WCtidvqdTt8l2KMQg                           Chevron Pitstop   
83      coVhQD_EAnCof_a8sGM03g                           Provence Bakery   
86      3jh0v0Gz7OOhDmWnQ7sP5g                            Vegas Vapolife   
118     -26MGfikhJiTfCI-GqmzhQ                        GoPro Door & Glass   
125     N9BN9ldVl1FNzcB9_eAstw               Red Rock Bowling UYE Part 2   
141     zhxnD7J5_sCrKSw5cwI9dQ                 Popeyes Louisiana Kitchen   
143     2kWrSFkIes_d2BMg4YrRtA                                 Pizza Hut   
145     6llKs7K_tn8ChXcIM-oTvg                              Sansei Japan   
147     ei7Sc2UrG4cdXcocfTrppQ                         Pariente Law Firm   
154     xinXcgLRuVjQ6W8ufxQxCw         Hoppy's Transmission & Automotive   
161     nqnYDW_FMwuTejAPNEOhqA         Seasonal Adventures Pumpkin Patch   
175     arx-ZLLBY9RwOo_NahD9-g              Executive Coach and Carriage   
182     Tjjj9XSBc9Hr_RCGD6JURQ  MGM Resorts International Contact Center   
186     A1R8iIeAFlbZWUhHlnaszw                                Kara Tiana   
197     YV9GVfmDSDM7HSV0jVdTOA                             El Pollo Loco   
203     F7OsiFk9aLZtqZczA84xpw                 Popeyes Louisiana Kitchen   
204     uE4H9oQikACJtu1ECBsoTQ                        Las Vegas BikeFest   
205     PqwEuhVLp4PzfAg5ROgTaA                 Walmart Auto Care Centers   
...                        ...                                       ...   
188462  HiecQOPC7Aj9sNg_h4gonw                       Vegas valley movers   
188463  V8jk9DuWpYB7YsSeDRCT5g  Schuck & Cho Group - 1st Priority Realty   
188464  pzNg_g9XpaHKuAY9b5ClIQ                           NY Hair Company   
188465  hSV-qwDq0G4UuyVtlQXUrQ           Air Wizards Heating and Cooling   
188475  YgD-tVUetABxykYP0P1VyQ                          Above and Beyond   
188487  8A8-xCeCZ3mKcpYT_P8_qQ                   A Robert Cromeans Salon   
188488  g62SlImzhs6_1t-knPjd8w      Red Square Restaurant & Vodka Lounge   
188497  UNsvHecpu_sPBeQGFxSCUA               Monthathong Thai Restaurant   
188498  rnNFE7-zE5BFKjFURBEpJw                     Polished3 Nails & Spa   
188499  CsLKFf9o7d9YZO2hsu6hzA               Green Valley Turf Equipment   
188500  bWZ6xFCL9FeAUPFmbAgAAw                       Williams Costume Co   
188502  B8zlK5jEGAUJtIfhLA71jw                              Art House LV   
188516  _eysP-l3yXpCqMHOQEptdQ                All About Beautiful Smiles   
188520  8w2Mzdz-JKy3qOpndK1Wqw                                    Subway   
188539  rbXaYPyC6qSYzeggPcbHYQ                           Paradigm Realty   
188541  _z0G1mVB_vQmT2aNqfZXKA                    Scooter Shop Las Vegas   
188547  qjyOjCHG9lOkZnAa8jIQ1g                             Master Donuts   
188548  wK6bv6_TKdbAswbMNfO_2w                               247 Techies   
188566  m75vszskLJ1a14Ybco4IaA          Louis Vuitton Las Vegas Bellagio   
188567  0zGeYN8ReYwVj27U7EHOJA                             American Cafe   
188568  v62o0cbntlpDXYaJtO9Lmw       Fort Apache Desert Inn Self Sto

<h4> Replace None or NA attributes with {}

In [8]:
df_2.replace('None','{}', inplace=True)
df_2.fillna('{}', inplace=True)
df_2

/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py:3798: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  method=method)
/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py:3790: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)


attributes
17      {'BusinessAcceptsCreditCards': 'True', 'Busine...
18                                                     {}
19      {'BikeParking': 'True', 'BusinessAcceptsCredit...
20                 {'BusinessAcceptsCreditCards': 'True'}
32      {'Alcohol': 'none', 'Ambience': "{'romantic': ...
33      {'Alcohol': 'beer_and_wine', 'Ambience': "{'ro...
44      {'BikeParking': 'True', 'BusinessAcceptsCredit...
45      {'BusinessAcceptsCreditCards': 'True', 'ByAppo...
50      {'BikeParking': 'True', 'BusinessAcceptsCredit...
52      {'BikeParking': 'True', 'BusinessAcceptsCredit...
58                                                     {}
61      {'HasTV': 'False', 'RestaurantsReservations': ...
65                 {'BusinessAcceptsCreditCards': 'True'}
83      {'BusinessAcceptsCreditCards': 'True', 'Busine...
86      {'BusinessAcceptsCreditCards': 'True', 'Restau...
118     {'BusinessAcceptsCreditCards': 'False', 'ByApp...
125     {'BikeParking': 'True', 'BusinessAcceptsCredit...
141     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
143     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
145     {'BusinessAcceptsCreditCards': 'True', 'GoodFo...
147                                                    {}
154                                                    {}
161     {'BikeParking': 'True', 'BusinessAcceptsCredit...
175                                                    {}
182                                                    {}
186     {'BusinessAcceptsCreditCards': 'True', 'ByAppo...
197     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
203     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
204                              {'GoodForKids': 'False'}
205                {'BusinessAcceptsCreditCards': 'True'}
...                                                   ...
188462  {'BusinessAcceptsBitcoin': 'False', 'BusinessA...
188463  {'BusinessAcceptsBitcoin': 'False', 'BusinessA...
188464  {'BikeParking': 'True', 'BusinessAcceptsBitcoi...
188465  {'BusinessAcceptsCreditCards': 'True', 'ByAppo...
188475  {'BusinessAcceptsCreditCards': 'True', 'Busine...
188487  {'BikeParking': 'False', 'BusinessAcceptsCredi...
188488  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188497  {'Alcohol': 'none', 'Ambience': "{'romantic': ...
188498  {'AcceptsInsurance': 'False', 'BikeParking': '...
188499  {'BusinessAcceptsCreditCards': 'True', 'Busine...
188500  {'BikeParking': 'True', 'BusinessAcceptsCredit...
188502  {'BikeParking': 'True', 'BusinessAcceptsCredit...
188516  {'AcceptsInsurance': 'True', 'ByAppointmentOnl...
188520  {'Alcohol': 'none', 'Ambience': "{'romantic': ...
188539  {'BusinessAcceptsBitcoin': 'False', 'BusinessA...
188541             {'BusinessAcceptsCreditCards': 'True'}
188547  {'BikeParking': 'True', 'BusinessAcceptsCredit...
188548  {'BusinessAcceptsBitcoin': 'False', 'BusinessA...
188566  {'BikeParking': 'False', 'BusinessAcceptsCredi...
188567  {'Ambience': "{'romantic': False, 'intimate': ...
188568             {'BusinessAcceptsCreditCards': 'True'}
188569  {'BikeParking': 'False', 'BusinessAcceptsCredi...
188570  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188572  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188573                           {'GoodForKids': 'False'}
188580  {'BusinessAcceptsCreditCards': 'True', 'ByAppo...
188582             {'BusinessAcceptsCreditCards': 'True'}
188583  {'BikeParking': 'True', 'BusinessAcceptsCredit...
188584  {'BikeParking': 'True', 'BusinessAcceptsCredit...
188592  {'BikeParking': 'True', 'BusinessAcceptsCredit...

[28853 rows x 1 columns]

<h4> Making a new dataframe out of attributes dictionary

In [9]:
cols=['BikeParking','BusinessAcceptsCreditCards','BusinessParking','GoodForKids','HasTV','NoiseLevel','OutdoorSeating','RestaurantsAttire','RestaurantsDelivery','RestaurantsGoodForGroups','RestaurantsPriceRange2','RestaurantsReservations','RestaurantsTakeOut']

df_3=pd.DataFrame(columns=cols)

for index, row in tqdm_notebook(df_2.iterrows()):
    string=ast.literal_eval(row.attributes)
    df_4=pd.DataFrame.from_dict([string])
    df_3=pd.concat([df_3,df_4], axis=0)
df_3

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


AcceptsInsurance AgesAllowed        Alcohol  \
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN           none   
0               NaN         NaN  beer_and_wine   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN           none   
0               NaN         NaN           none   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN           none   
0               NaN         NaN           none   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
..              ...         ...            ...   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN           none   
0             False         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0              True         NaN            NaN   
0               NaN         NaN           none   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN       full_bar   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   

                                             Ambience   BYOB  BYOBCorkage  \
0                                                 NaN    NaN          NaN   
0                                                 NaN    NaN          NaN   
0                                                 NaN    NaN          NaN   
0                                                 NaN    NaN          NaN   
0   {'romantic': False, 'intimate': False, 'classy...    NaN          NaN   
0   {'romantic': False, 'intimate': False, 'classy...    NaN          NaN   
0                                                 NaN    NaN          NaN   
0                                                 NaN    NaN          NaN   
0                                                 NaN    NaN          NaN   
0                                                 NaN    NaN          NaN   
0                                                 NaN  

<h4>  Concatenate New Attributes Columns and older remaining columns

In [41]:
df_1.reset_index(drop=True, inplace=True)
df_3.reset_index(drop=True, inplace=True)
dat1 = pd.concat([df_1, df_3], axis=1)
df_1.shape,df_3.shape,dat1.shape
dat1

BusinessId                            RestaurantName  \
0      hTzcHtk4-0QJnFUbkKpd5Q                               Citi Trends   
1      UwIpS9UKsPiKAv1fiEYhqg             Nevada Title And Payday Loans   
2      vJIuDBdu01vCA8y1fwR1OQ                                CakesbyToi   
3      YZCHr68c5aEVHz0bkq9K2g                         Park Stone Pavers   
4      kgffcoxT6BQp-gJ-UQ7Czw                                    Subway   
5      0jtRI7hVMpQHpUVtUy4ITw                    Omelet House Summerlin   
6      0i6GlR5YTCMlwthjqw6ZTQ                    Cinthya's Beauty Salon   
7      oSS0p8TeF9BTTD7QWtO6gg                           Aria Remodeling   
8      DR30lzIHVTF6xhyMI-3IlQ                    Not Just Antiques Mart   
9      VVtPNiqwtR_Os7J51mANGQ           JAM Scooter Rental Of Las Vegas   
10     syCI-5YJ8VJhFzHlzfpP0g                          Shower Solutions   
11     JJEx5wIqs9iGGATOagE8Sg                  Baja Fresh Mexican Grill   
12     JbIi9WCtidvqdTt8l2KMQg                           Chevron Pitstop   
13     coVhQD_EAnCof_a8sGM03g                           Provence Bakery   
14     3jh0v0Gz7OOhDmWnQ7sP5g                            Vegas Vapolife   
15     -26MGfikhJiTfCI-GqmzhQ                        GoPro Door & Glass   
16     N9BN9ldVl1FNzcB9_eAstw               Red Rock Bowling UYE Part 2   
17     zhxnD7J5_sCrKSw5cwI9dQ                 Popeyes Louisiana Kitchen   
18     2kWrSFkIes_d2BMg4YrRtA                                 Pizza Hut   
19     6llKs7K_tn8ChXcIM-oTvg                              Sansei Japan   
20     ei7Sc2UrG4cdXcocfTrppQ                         Pariente Law Firm   
21     xinXcgLRuVjQ6W8ufxQxCw         Hoppy's Transmission & Automotive   
22     nqnYDW_FMwuTejAPNEOhqA         Seasonal Adventures Pumpkin Patch   
23     arx-ZLLBY9RwOo_NahD9-g              Executive Coach and Carriage   
24     Tjjj9XSBc9Hr_RCGD6JURQ  MGM Resorts International Contact Center   
25     A1R8iIeAFlbZWUhHlnaszw                                Kara Tiana   
26     YV9GVfmDSDM7HSV0jVdTOA                             El Pollo Loco   
27     F7OsiFk9aLZtqZczA84xpw                 Popeyes Louisiana Kitchen   
28     uE4H9oQikACJtu1ECBsoTQ                        Las Vegas BikeFest   
29     PqwEuhVLp4PzfAg5ROgTaA                 Walmart Auto Care Centers   
...                       ...                                       ...   
28823  HiecQOPC7Aj9sNg_h4gonw                       Vegas valley movers   
28824  V8jk9DuWpYB7YsSeDRCT5g  Schuck & Cho Group - 1st Priority Realty   
28825  pzNg_g9XpaHKuAY9b5ClIQ                           NY Hair Company   
28826  hSV-qwDq0G4UuyVtlQXUrQ           Air Wizards Heating and Cooling   
28827  YgD-tVUetABxykYP0P1VyQ                          Above and Beyond   
28828  8A8-xCeCZ3mKcpYT_P8_qQ                   A Robert Cromeans Salon   
28829  g62SlImzhs6_1t-knPjd8w      Red Square Restaurant & Vodka Lounge   
28830  UNsvHecpu_sPBeQGFxSCUA               Monthathong Thai Restaurant   
28831  rnNFE7-zE5BFKjFURBEpJw                     Polished3 Nails & Spa   
28832  CsLKFf9o7d9YZO2hsu6hzA               Green Valley Turf Equipment   
28833  bWZ6xFCL9FeAUPFmbAgAAw                       Williams Costume Co   
28834  B8zlK5jEGAUJtIfhLA71jw                              Art House LV   
28835  _eysP-l3yXpCqMHOQEptdQ                All About Beautiful Smiles   
28836  8w2Mzdz-JKy3qOpndK1Wqw                                    Subway   
28837  rbXaYPyC6qSYzeggPcbHYQ                           Paradigm Realty   
28838  _z0G1mVB_vQmT2aNqfZXKA                    Scooter Shop Las Vegas   
28839  qjyOjCHG9lOkZnAa8jIQ1g                             Master Donuts   
28840  wK6bv6_TKdbAswbMNfO_2w                               247 Techies   
28841  m75vszskLJ1a14Ybco4IaA          Louis Vuitton Las Vegas Bellagio   
28842  0zGeYN8ReYwVj27U7EHOJA                             American Cafe   
28843  v62o0cbntlpDXYaJtO9Lmw       Fort Apache Desert Inn Self Storage   
28844  CorrByydi35r-6SvmhYFHA               

<h3> Mapping Values

<h4> All True=1, False=0

In [42]:
dat1.replace('True',1,inplace=True)
dat1.replace('False',0,inplace=True)
dat1

BusinessId                            RestaurantName  \
0      hTzcHtk4-0QJnFUbkKpd5Q                               Citi Trends   
1      UwIpS9UKsPiKAv1fiEYhqg             Nevada Title And Payday Loans   
2      vJIuDBdu01vCA8y1fwR1OQ                                CakesbyToi   
3      YZCHr68c5aEVHz0bkq9K2g                         Park Stone Pavers   
4      kgffcoxT6BQp-gJ-UQ7Czw                                    Subway   
5      0jtRI7hVMpQHpUVtUy4ITw                    Omelet House Summerlin   
6      0i6GlR5YTCMlwthjqw6ZTQ                    Cinthya's Beauty Salon   
7      oSS0p8TeF9BTTD7QWtO6gg                           Aria Remodeling   
8      DR30lzIHVTF6xhyMI-3IlQ                    Not Just Antiques Mart   
9      VVtPNiqwtR_Os7J51mANGQ           JAM Scooter Rental Of Las Vegas   
10     syCI-5YJ8VJhFzHlzfpP0g                          Shower Solutions   
11     JJEx5wIqs9iGGATOagE8Sg                  Baja Fresh Mexican Grill   
12     JbIi9WCtidvqdTt8l2KMQg                           Chevron Pitstop   
13     coVhQD_EAnCof_a8sGM03g                           Provence Bakery   
14     3jh0v0Gz7OOhDmWnQ7sP5g                            Vegas Vapolife   
15     -26MGfikhJiTfCI-GqmzhQ                        GoPro Door & Glass   
16     N9BN9ldVl1FNzcB9_eAstw               Red Rock Bowling UYE Part 2   
17     zhxnD7J5_sCrKSw5cwI9dQ                 Popeyes Louisiana Kitchen   
18     2kWrSFkIes_d2BMg4YrRtA                                 Pizza Hut   
19     6llKs7K_tn8ChXcIM-oTvg                              Sansei Japan   
20     ei7Sc2UrG4cdXcocfTrppQ                         Pariente Law Firm   
21     xinXcgLRuVjQ6W8ufxQxCw         Hoppy's Transmission & Automotive   
22     nqnYDW_FMwuTejAPNEOhqA         Seasonal Adventures Pumpkin Patch   
23     arx-ZLLBY9RwOo_NahD9-g              Executive Coach and Carriage   
24     Tjjj9XSBc9Hr_RCGD6JURQ  MGM Resorts International Contact Center   
25     A1R8iIeAFlbZWUhHlnaszw                                Kara Tiana   
26     YV9GVfmDSDM7HSV0jVdTOA                             El Pollo Loco   
27     F7OsiFk9aLZtqZczA84xpw                 Popeyes Louisiana Kitchen   
28     uE4H9oQikACJtu1ECBsoTQ                        Las Vegas BikeFest   
29     PqwEuhVLp4PzfAg5ROgTaA                 Walmart Auto Care Centers   
...                       ...                                       ...   
28823  HiecQOPC7Aj9sNg_h4gonw                       Vegas valley movers   
28824  V8jk9DuWpYB7YsSeDRCT5g  Schuck & Cho Group - 1st Priority Realty   
28825  pzNg_g9XpaHKuAY9b5ClIQ                           NY Hair Company   
28826  hSV-qwDq0G4UuyVtlQXUrQ           Air Wizards Heating and Cooling   
28827  YgD-tVUetABxykYP0P1VyQ                          Above and Beyond   
28828  8A8-xCeCZ3mKcpYT_P8_qQ                   A Robert Cromeans Salon   
28829  g62SlImzhs6_1t-knPjd8w      Red Square Restaurant & Vodka Lounge   
28830  UNsvHecpu_sPBeQGFxSCUA               Monthathong Thai Restaurant   
28831  rnNFE7-zE5BFKjFURBEpJw                     Polished3 Nails & Spa   
28832  CsLKFf9o7d9YZO2hsu6hzA               Green Valley Turf Equipment   
28833  bWZ6xFCL9FeAUPFmbAgAAw                       Williams Costume Co   
28834  B8zlK5jEGAUJtIfhLA71jw                              Art House LV   
28835  _eysP-l3yXpCqMHOQEptdQ                All About Beautiful Smiles   
28836  8w2Mzdz-JKy3qOpndK1Wqw                                    Subway   
28837  rbXaYPyC6qSYzeggPcbHYQ                           Paradigm Realty   
28838  _z0G1mVB_vQmT2aNqfZXKA                    Scooter Shop Las Vegas   
28839  qjyOjCHG9lOkZnAa8jIQ1g                             Master Donuts   
28840  wK6bv6_TKdbAswbMNfO_2w                               247 Techies   
28841  m75vszskLJ1a14Ybco4IaA          Louis Vuitton Las Vegas Bellagio   
28842  0zGeYN8ReYwVj27U7EHOJA                             American Cafe   
28843  v62o0cbntlpDXYaJtO9Lmw       Fort Apache Desert Inn Self Storage   
28844  CorrByydi35r-6SvmhYFHA               

In [43]:
dat1.columns.values

array(['BusinessId', 'RestaurantName', 'Neighborhood', 'Address', 'City',
       'State', 'Zip', 'Stars', 'ReviewCount', 'AcceptsInsurance',
       'AgesAllowed', 'Alcohol', 'Ambience', 'BYOB', 'BYOBCorkage',
       'BestNights', 'BikeParking', 'BusinessAcceptsBitcoin',
       'BusinessAcceptsCreditCards', 'BusinessParking',
       'ByAppointmentOnly', 'Caters', 'CoatCheck', 'Corkage',
       'DietaryRestrictions', 'DogsAllowed', 'DriveThru', 'GoodForDancing',
       'GoodForKids', 'GoodForMeal', 'HairSpecializesIn', 'HappyHour',
       'HasTV', 'Music', 'NoiseLevel', 'Open24Hours', 'OutdoorSeating',
       'RestaurantsAttire', 'RestaurantsCounterService',
       'RestaurantsDelivery', 'RestaurantsGoodForGroups',
       'RestaurantsPriceRange2', 'RestaurantsReservations',
       'RestaurantsTableService', 'RestaurantsTakeOut', 'Smoking',
       'WheelchairAccessible', 'WiFi'], dtype=object)

In [44]:
dat1.HasTV.unique()
dat1.WheelchairAccessible.unique()
dat1.HappyHour.unique()
dat1.GoodForDancing.unique()
dat1.DriveThru.unique()
dat1.DogsAllowed.unique()
dat1.Corkage.unique()
dat1.RestaurantsReservations.unique()
dat1.RestaurantsTableService.unique()
dat1.RestaurantsTakeOut.unique()
dat1.RestaurantsCounterService.unique()
dat1.RestaurantsDelivery.unique()
dat1.RestaurantsGoodForGroups.unique()
dat1.CoatCheck.unique()
dat1.Caters.unique()
dat1.ByAppointmentOnly.unique()
dat1.BusinessAcceptsCreditCards.unique()
dat1.BusinessAcceptsBitcoin.unique()
dat1.BikeParking.unique()
dat1.BYOB.unique()
dat1.GoodForKids.unique()
dat1.Open24Hours.unique()
dat1.OutdoorSeating.unique()
dat1.AcceptsInsurance.unique()

array([ nan,   1.,   0.])

In [45]:
dat1.WiFi.unique()
#Mapping : no=0,free=1, paid=2
dat1.WiFi.replace('no',0,inplace=True)
dat1.WiFi.replace('free',1,inplace=True)
dat1.WiFi.replace('paid',2,inplace=True)
dat1.WiFi.unique()

array([ nan,   0.,   1.,   2.])

In [46]:
dat1.Smoking.unique()
#Mapping : no=0, yes=1, outdoor=2
dat1.Smoking.replace('no',0,inplace=True)
dat1.Smoking.replace('yes',1,inplace=True)
dat1.Smoking.replace('outdoor',2,inplace=True)
dat1.Smoking.unique()

array([ nan,   0.,   1.,   2.])

In [47]:
#Dont Know what they represent
dat1.RestaurantsPriceRange2.unique()

array(['2', nan, '1', '3', '4'], dtype=object)

In [48]:
dat1.RestaurantsAttire.unique()
#Mapping : casual=0, dressy=1, formal=2
dat1.RestaurantsAttire.replace('casual',0,inplace=True)
dat1.RestaurantsAttire.replace('dressy',1,inplace=True)
dat1.RestaurantsAttire.replace('formal',2,inplace=True)
dat1.RestaurantsAttire.unique()

array([ nan,   0.,   1.,   2.])

In [49]:
dat1.NoiseLevel.unique()
#Mapping : quiet=0,average=1, loud=2, very_loud=3
dat1.NoiseLevel.replace('quiet',0,inplace=True)
dat1.NoiseLevel.replace('average',1,inplace=True)
dat1.NoiseLevel.replace('loud',2,inplace=True)
dat1.NoiseLevel.replace('very_loud',3,inplace=True)
dat1.NoiseLevel.unique()

array([ nan,   1.,   2.,   0.,   3.])

In [50]:
dat1.BYOBCorkage.unique()
#Mapping : no->0, yes_free->1, yes_corkage->2
dat1.BYOBCorkage.replace('no',0,inplace=True)
dat1.BYOBCorkage.replace('yes_free',1,inplace=True)
dat1.BYOBCorkage.replace('yes_corkage',2,inplace=True)
dat1.BYOBCorkage.unique()

array([ nan,   1.,   0.,   2.])

In [51]:
#Range of Ages Allowed
dat1.AgesAllowed.unique()
#Mapping : allages->0,18plus->1,21plus->2
dat1.AgesAllowed.replace('allages',0,inplace=True)
dat1.AgesAllowed.replace('18plus',1,inplace=True)
dat1.AgesAllowed.replace('21plus',2,inplace=True)
dat1.AgesAllowed.unique()

array([ nan,   2.,   0.,   1.])

In [52]:
#Range of Alcohol
dat1.Alcohol.unique()
#Mapping : none->0, beer_and_wine->1,full_bar->2
dat1.Alcohol.replace('none',0,inplace=True)
dat1.Alcohol.replace('beer_and_wine',1,inplace=True)
dat1.Alcohol.replace('full_bar',2,inplace=True)
dat1.Alcohol.unique()

array([ nan,   0.,   1.,   2.])

In [57]:
#Mapping - count number of True Values - number of best nights in a week
for row in tqdm_notebook(dat1.BestNights):
    if type(row)==type(''):
        dat1.BestNights.replace(row,row.count('True'),inplace=True)   
dat1.BestNights.unique()

array([ nan,   3.,   1.,   0.,   2.])

In [58]:
#Mapping - count number of True Values - number of types of ambiences it offers
for row in tqdm_notebook(dat1.Ambience):
    if type(row)==type(''):
        dat1.Ambience.replace(row,row.count('True'),inplace=True)   
dat1.Ambience.unique()

array([ nan,   1.,   0.,   2.,   3.,   4.,   5.,   6.,   7.])

In [59]:
#Mapping - count number of True Values - number of types of parkings available
#eg- {'garage': True, 'street': False, 'validated': False, 'lot': False, 'valet': False} has 1 type of parking
# and "{'garage': True, 'street': True, 'validated': False, 'lot': False, 'valet': True}" has 3
for row in tqdm_notebook(dat1.BusinessParking):
    if type(row)==type(''):
        dat1.BusinessParking.replace(row,row.count('True'),inplace=True)   
dat1.BusinessParking.unique()

array([  0.,  nan,   1.,   3.,   2.,   4.,   5.])

In [60]:
for row in tqdm_notebook(dat1.GoodForMeal):
    if type(row)==type(''):
        dat1.GoodForMeal.replace(row,row.count('True'),inplace=True)   
dat1.GoodForMeal.unique()

HBox(children=(IntProgress(value=0, max=28853), HTML(value='')))

array([ nan,   3.,   0.,   2.,   1.,   4.,   6.,   5.])

In [61]:
for row in tqdm_notebook(dat1.HairSpecializesIn):
    if type(row)==type(''):
        dat1.HairSpecializesIn.replace(row,row.count('True'),inplace=True)   
dat1.HairSpecializesIn.unique()

HBox(children=(IntProgress(value=0, max=28853), HTML(value='')))

array([ nan,   1.,   6.,   5.,   8.,   4.,   0.,   3.,   7.,   2.])

In [62]:
for row in tqdm_notebook(dat1.Music):
    if type(row)==type(''):
        dat1.Music.replace(row,row.count('True'),inplace=True)   
dat1.Music.unique()

HBox(children=(IntProgress(value=0, max=28853), HTML(value='')))

array([ nan,   0.,   1.,   2.,   3.,   4.,   5.,   6.])

In [64]:
#dat1.DietaryRestrictions.unique()
#7 types/combos of dietry restrictions. These are as follows -
dat1.DietaryRestrictions.replace("{'dairy-free': True, 'gluten-free': False, 'vegan': True, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': True}",0,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': False, 'gluten-free': False, 'vegan': False, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': True}",1,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': True, 'gluten-free': False, 'vegan': True, 'kosher': False, 'halal': False, 'soy-free': True, 'vegetarian': True}",2,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': False, 'gluten-free': False, 'vegan': True, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': True}",3,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': False, 'gluten-free': False, 'vegan': True, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': False}",4,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': True, 'gluten-free': False, 'vegan': False, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': True}",5,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': False, 'gluten-free': True, 'vegan': False, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': False}",6,inplace=True)
dat1.DietaryRestrictions.unique()

array([ nan,   0.,   1.,   2.,   3.,   4.,   5.,   6.])

In [66]:
dat1.fillna('Null', inplace=True)


In [67]:
dat1.to_csv('Temp_Business.csv',',')