<h2>lasVegas.csv Business Processing

<h4>Import Statements

In [1]:
import pandas as pd
import json
import numpy as np
import ast
from tqdm import tqdm_notebook

<h4>Reading lasVegas.csv into Pandas Dataframe df

In [2]:
df=pd.DataFrame.from_csv('/home/rim/INF-Project/preprocessed_lasVegas.csv')
df.shape

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


(8808, 15)

In [3]:
#Reading from yelp json
#df=pd.read_json('/home/rim/Desktop/Yelp dataset/yelp_academic_dataset_business.json',lines=True)
#df.shape

In [4]:
#df.columns.values
#df.loc[df['state'] == 'CA']

<h4>Select required columns and rename columns to standard names

In [5]:
df=df[['business_id','name','neighborhood','address','city','state','postal_code','stars','review_count','attributes']]
df.columns=['BusinessId',"RestaurantName",'Neighborhood',"Address",'City','State','Zip','Stars','ReviewCount','attributes']
df.columns.values

array(['BusinessId', 'RestaurantName', 'Neighborhood', 'Address', 'City',
       'State', 'Zip', 'Stars', 'ReviewCount', 'attributes'], dtype=object)

<h4>Divide df into 2 parts - attributes and the rest

In [6]:
df_1=df[['BusinessId',"RestaurantName",'Neighborhood',"Address",'City','State','Zip','Stars','ReviewCount']]
df_2=df[['attributes']]

<h4> Replace blank with ''

In [7]:
df_1.fillna('', inplace=True)
df_1

/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py:3790: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)


BusinessId                          RestaurantName  \
19      vJIuDBdu01vCA8y1fwR1OQ                              CakesbyToi   
32      kgffcoxT6BQp-gJ-UQ7Czw                                  Subway   
33      0jtRI7hVMpQHpUVtUy4ITw                  Omelet House Summerlin   
61      JJEx5wIqs9iGGATOagE8Sg                Baja Fresh Mexican Grill   
83      coVhQD_EAnCof_a8sGM03g                         Provence Bakery   
141     zhxnD7J5_sCrKSw5cwI9dQ               Popeyes Louisiana Kitchen   
143     2kWrSFkIes_d2BMg4YrRtA                               Pizza Hut   
145     6llKs7K_tn8ChXcIM-oTvg                            Sansei Japan   
161     nqnYDW_FMwuTejAPNEOhqA       Seasonal Adventures Pumpkin Patch   
197     YV9GVfmDSDM7HSV0jVdTOA                           El Pollo Loco   
203     F7OsiFk9aLZtqZczA84xpw               Popeyes Louisiana Kitchen   
249     XeDLyY2a7nZ3IEY4RYslXA                 Chicago Brewing Company   
257     MDVbJicJvqaO4WGx0vEabQ                                 Chili's   
271     AAcaGYggq4RBbFdEueB2qw                    Green Valley Grocery   
277     Zh6fxrqsKqdSVmTK3roxBQ             Triumph Property Management   
279     sOkQ2Y1-D8h18oN5NgxuLg  Haddies Car Wash and Convenience store   
307     OyJDaAAMr220qkZsovCARQ                               Starbucks   
325     lv5Bnqlt93NnvNJ2oNcQ8Q                  Los Cucos Mexican Cafe   
391     D1TaFES4phv65RmsM8VCiA                          Domino's Pizza   
397     vTch8eXerkbaJbmkmYwCEw                      One Six Sky Lounge   
497     glkEaoxbewiSMBiXs945JA                             800 Degrees   
503     3TX-5V6MuGPKnZv6gW1nsg                                Cardenas   
539     lYCeqldIiOggsbByH3RRhw                             Metro Pizza   
541     tA1oBX1q6Aqj8UG3y-SqTA                                IT'SUGAR   
605     juuv0QPE_MfnVjevQTpCDg                       Manhattan Streets   
630     DbK9fyJq4O4zfT1jv6JOhw                 Pam Real Thai Las Vegas   
758     PChG1Dm0A6AXIXkXGVK8Fw                              Sasa Sushi   
764     owxcYAUca_6K6BAUX4V48w                           D'Pinoy Joint   
912     WSGHEQdcdbBWXDpna99EiQ                        Teriyaki Madness   
949     0aDCv4zPhzy7RklHDrnKQg                          Lucie's Lounge   
...                        ...                                     ...   
187929  diFj7LtBvNcgMy4Pb4_m0g   ROYCE' Las Vegas at Fashion Show Mall   
188066  6xgcHeLad-VaoTIQewK84A                         N9NE Steakhouse   
188067  _Jt9CLSL2sqF-yCNel9D-g                             Casa Robles   
188103  5FgLuegzxBvRFw5dTuETEw                             The Chelsea   
188155  dTsyfvRfN-zFdsgIDuQllQ                           Alder & Birch   
188156  OaHfq01gm8PTYkJ36k1feg     Michael T's Steaks, Ribs, & Burgers   
188157  brB2AfUTKumrRNanOZVw4w                             Scarlet Bar   
188159  ZyTrka-HiVb6Ckcl0rDaNA               Popeyes Louisiana Kitchen   
188254  vodCM302JJ_P9yJt1WuH_w                                Vege-Way   
188255  YAiHkQAQ9sm23V1CyNT2zQ                     Bogey's Bar & Grill   
188309  cYwJA2A6I12KNkm2rtXd5g                     Gordon Ramsay BurGR   
188310  RSPEJeFTKs1BsiVgjHp1WQ                  Spago by Wolfgang Puck   
188317  YhCh4mAs52COFPNLJUOFWQ                               Tonic Bar   
188318  SUTTl_NCJb5JYdlMBnuVxg                       Wetzel's Pretzels   
188319  swtA5YoSGm0V5esQuDm2NQ                                  Social   
188344  YC1FXuG7IQneHnhbHT0XcQ                           The Lobby Bar   
188380  WEPqQjRGviPyCKEmPhALSw                      The Coachman's Inn   
188417  ZVetFAAt0_j0tEqiakpecA                         Jack in the Box   
188418  WUswpeAjbiww_xkSS8jTEA          Pupusas La Familiar Restaurant   
188445  5iAFiMPfitcYDMeII5_dnQ                           Auntie Anne's   
188447  qtc1YZix_5lHBJTZq7DOpA                               Zeffirino   
188448  PDIh1lVtKlUqPJROXYJQvQ                                     FIX   
188450  TEpHybMZew9kKadv

<h4> Replace None or NA attributes with {}

In [8]:
df_2.replace('None','{}', inplace=True)
df_2.fillna('{}', inplace=True)
df_2

/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py:3798: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  method=method)
/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py:3790: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)


attributes
19      {'BikeParking': 'True', 'BusinessAcceptsCredit...
32      {'Alcohol': 'none', 'Ambience': "{'romantic': ...
33      {'Alcohol': 'beer_and_wine', 'Ambience': "{'ro...
61      {'HasTV': 'False', 'RestaurantsReservations': ...
83      {'BusinessAcceptsCreditCards': 'True', 'Busine...
141     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
143     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
145     {'BusinessAcceptsCreditCards': 'True', 'GoodFo...
161     {'BikeParking': 'True', 'BusinessAcceptsCredit...
197     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
203     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
249     {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
257     {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
271     {'BikeParking': 'False', 'BusinessAcceptsCredi...
277     {'BusinessAcceptsBitcoin': 'False', 'BusinessA...
279     {'Ambience': "{'romantic': False, 'intimate': ...
307     {'BikeParking': 'True', 'BusinessAcceptsCredit...
325     {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
391     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
397     {'Alcohol': 'full_bar', 'BestNights': "{'monda...
497     {'Alcohol': 'beer_and_wine', 'Ambience': "{'ro...
503     {'BikeParking': 'True', 'BusinessAcceptsCredit...
539     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
541     {'BikeParking': 'True', 'BusinessAcceptsBitcoi...
605     {'Alcohol': 'beer_and_wine', 'Ambience': "{'ro...
630     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
758     {'Alcohol': 'beer_and_wine', 'Ambience': "{'ro...
764     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
912     {'Alcohol': 'none', 'Ambience': "{'romantic': ...
949     {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
...                                                   ...
187929  {'BusinessAcceptsCreditCards': 'True', 'Busine...
188066  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188067  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188103  {'BusinessAcceptsCreditCards': 'True', 'Wheelc...
188155  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188156  {'Alcohol': 'full_bar', 'BestNights': "{'monda...
188157  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188159  {'Alcohol': 'none', 'Ambience': "{'romantic': ...
188254  {'Alcohol': 'none', 'Ambience': "{'romantic': ...
188255  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188309  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188310  {'Ambience': "{'romantic': False, 'intimate': ...
188317  {'Alcohol': 'full_bar', 'BusinessAcceptsCredit...
188318  {'BikeParking': 'False', 'BusinessAcceptsBitco...
188319  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188344  {'BusinessAcceptsCreditCards': 'True', 'GoodFo...
188380  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188417  {'Alcohol': 'none', 'Ambience': "{'romantic': ...
188418  {'Alcohol': 'none', 'Ambience': "{'romantic': ...
188445  {'Ambience': "{'romantic': False, 'intimate': ...
188447  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188448  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188450  {'BikeParking': 'True', 'BusinessAcceptsBitcoi...
188488  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188497  {'Alcohol': 'none', 'Ambience': "{'romantic': ...
188520  {'Alcohol': 'none', 'Ambience': "{'romantic': ...
188547  {'BikeParking': 'True', 'BusinessAcceptsCredit...
188567  {'Ambience': "{'romantic': False, 'intimate': ...
188570  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...
188572  {'Alcohol': 'full_bar', 'Ambience': "{'romanti...

[8808 rows x 1 columns]

<h4> Making a new dataframe out of attributes dictionary

In [9]:
cols=['BikeParking','BusinessAcceptsCreditCards','BusinessParking','GoodForKids','HasTV','NoiseLevel','OutdoorSeating','RestaurantsAttire','RestaurantsDelivery','RestaurantsGoodForGroups','RestaurantsPriceRange2','RestaurantsReservations','RestaurantsTakeOut']

df_3=pd.DataFrame(columns=cols)

for index, row in tqdm_notebook(df_2.iterrows()):
    string=ast.literal_eval(row.attributes)
    df_4=pd.DataFrame.from_dict([string])
    df_3=pd.concat([df_3,df_4], axis=0)
df_3

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


AcceptsInsurance AgesAllowed        Alcohol  \
0               NaN         NaN            NaN   
0               NaN         NaN           none   
0               NaN         NaN  beer_and_wine   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN           none   
0               NaN         NaN           none   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN           none   
0               NaN         NaN           none   
0               NaN         NaN       full_bar   
0               NaN         NaN       full_bar   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN           none   
0               NaN         NaN       full_bar   
0               NaN         NaN  beer_and_wine   
0               NaN         NaN            NaN   
0               NaN         NaN           none   
0               NaN         NaN            NaN   
0               NaN         NaN  beer_and_wine   
0               NaN         NaN           none   
0               NaN         NaN  beer_and_wine   
0               NaN         NaN           none   
0               NaN         NaN           none   
0               NaN         NaN       full_bar   
..              ...         ...            ...   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN       full_bar   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN       full_bar   
0               NaN         NaN       full_bar   
0               NaN         NaN           none   
0               NaN         NaN           none   
0               NaN         NaN       full_bar   
0               NaN         NaN       full_bar   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN           none   
0               NaN         NaN           none   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN       full_bar   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN           none   
0               NaN         NaN           none   
0               NaN         NaN            NaN   
0               NaN         NaN            NaN   
0               NaN         NaN       full_bar   
0               NaN         NaN       full_bar   

                                             Ambience   BYOB  BYOBCorkage  \
0                                                 NaN    NaN          NaN   
0   {'romantic': False, 'intimate': False, 'classy...    NaN          NaN   
0   {'romantic': False, 'intimate': False, 'classy...    NaN          NaN   
0                                                 NaN    NaN          NaN   
0                                                 NaN    NaN          NaN   
0   {'romantic': False, 'intimate': False, 'classy...    NaN          NaN   
0   {'romantic': False, 'intimate': False, 'classy...    NaN          NaN   
0                                                 NaN    NaN          NaN   
0                                                 NaN    NaN          NaN   
0   {'romantic': False, 'intimate': False, 'classy...    NaN          NaN   
0   {'romantic': False, 'intimate': False, 'classy...  

<h4>  Concatenate New Attributes Columns and older remaining columns

In [10]:
df_1.reset_index(drop=True, inplace=True)
df_3.reset_index(drop=True, inplace=True)
dat1 = pd.concat([df_1, df_3], axis=1)
df_1.shape,df_3.shape,dat1.shape
dat1

BusinessId                          RestaurantName  \
0     vJIuDBdu01vCA8y1fwR1OQ                              CakesbyToi   
1     kgffcoxT6BQp-gJ-UQ7Czw                                  Subway   
2     0jtRI7hVMpQHpUVtUy4ITw                  Omelet House Summerlin   
3     JJEx5wIqs9iGGATOagE8Sg                Baja Fresh Mexican Grill   
4     coVhQD_EAnCof_a8sGM03g                         Provence Bakery   
5     zhxnD7J5_sCrKSw5cwI9dQ               Popeyes Louisiana Kitchen   
6     2kWrSFkIes_d2BMg4YrRtA                               Pizza Hut   
7     6llKs7K_tn8ChXcIM-oTvg                            Sansei Japan   
8     nqnYDW_FMwuTejAPNEOhqA       Seasonal Adventures Pumpkin Patch   
9     YV9GVfmDSDM7HSV0jVdTOA                           El Pollo Loco   
10    F7OsiFk9aLZtqZczA84xpw               Popeyes Louisiana Kitchen   
11    XeDLyY2a7nZ3IEY4RYslXA                 Chicago Brewing Company   
12    MDVbJicJvqaO4WGx0vEabQ                                 Chili's   
13    AAcaGYggq4RBbFdEueB2qw                    Green Valley Grocery   
14    Zh6fxrqsKqdSVmTK3roxBQ             Triumph Property Management   
15    sOkQ2Y1-D8h18oN5NgxuLg  Haddies Car Wash and Convenience store   
16    OyJDaAAMr220qkZsovCARQ                               Starbucks   
17    lv5Bnqlt93NnvNJ2oNcQ8Q                  Los Cucos Mexican Cafe   
18    D1TaFES4phv65RmsM8VCiA                          Domino's Pizza   
19    vTch8eXerkbaJbmkmYwCEw                      One Six Sky Lounge   
20    glkEaoxbewiSMBiXs945JA                             800 Degrees   
21    3TX-5V6MuGPKnZv6gW1nsg                                Cardenas   
22    lYCeqldIiOggsbByH3RRhw                             Metro Pizza   
23    tA1oBX1q6Aqj8UG3y-SqTA                                IT'SUGAR   
24    juuv0QPE_MfnVjevQTpCDg                       Manhattan Streets   
25    DbK9fyJq4O4zfT1jv6JOhw                 Pam Real Thai Las Vegas   
26    PChG1Dm0A6AXIXkXGVK8Fw                              Sasa Sushi   
27    owxcYAUca_6K6BAUX4V48w                           D'Pinoy Joint   
28    WSGHEQdcdbBWXDpna99EiQ                        Teriyaki Madness   
29    0aDCv4zPhzy7RklHDrnKQg                          Lucie's Lounge   
...                      ...                                     ...   
8778  diFj7LtBvNcgMy4Pb4_m0g   ROYCE' Las Vegas at Fashion Show Mall   
8779  6xgcHeLad-VaoTIQewK84A                         N9NE Steakhouse   
8780  _Jt9CLSL2sqF-yCNel9D-g                             Casa Robles   
8781  5FgLuegzxBvRFw5dTuETEw                             The Chelsea   
8782  dTsyfvRfN-zFdsgIDuQllQ                           Alder & Birch   
8783  OaHfq01gm8PTYkJ36k1feg     Michael T's Steaks, Ribs, & Burgers   
8784  brB2AfUTKumrRNanOZVw4w                             Scarlet Bar   
8785  ZyTrka-HiVb6Ckcl0rDaNA               Popeyes Louisiana Kitchen   
8786  vodCM302JJ_P9yJt1WuH_w                                Vege-Way   
8787  YAiHkQAQ9sm23V1CyNT2zQ                     Bogey's Bar & Grill   
8788  cYwJA2A6I12KNkm2rtXd5g                     Gordon Ramsay BurGR   
8789  RSPEJeFTKs1BsiVgjHp1WQ                  Spago by Wolfgang Puck   
8790  YhCh4mAs52COFPNLJUOFWQ                               Tonic Bar   
8791  SUTTl_NCJb5JYdlMBnuVxg                       Wetzel's Pretzels   
8792  swtA5YoSGm0V5esQuDm2NQ                                  Social   
8793  YC1FXuG7IQneHnhbHT0XcQ                           The Lobby Bar   
8794  WEPqQjRGviPyCKEmPhALSw                      The Coachman's Inn   
8795  ZVetFAAt0_j0tEqiakpecA                         Jack in the Box   
8796  WUswpeAjbiww_xkSS8jTEA          Pupusas La Familiar Restaurant   
8797  5iAFiMPfitcYDMeII5_dnQ                           Auntie Anne's   
8798  qtc1YZix_5lHBJTZq7DOpA                               Zeffirino   
8799  PDIh1lVtKlUqPJROXYJQvQ                                     FIX   
8800  TEpHybMZew9kKadvseEbEQ                             Kung Fu Tea   
8801  g62SlImzhs6_1t-knPjd8w    Red Square Restaurant & Vo

<h3> Mapping Values

<h4> All True=1, False=0

In [11]:
dat1.replace('True',1,inplace=True)
dat1.replace('False',0,inplace=True)
dat1

BusinessId                          RestaurantName  \
0     vJIuDBdu01vCA8y1fwR1OQ                              CakesbyToi   
1     kgffcoxT6BQp-gJ-UQ7Czw                                  Subway   
2     0jtRI7hVMpQHpUVtUy4ITw                  Omelet House Summerlin   
3     JJEx5wIqs9iGGATOagE8Sg                Baja Fresh Mexican Grill   
4     coVhQD_EAnCof_a8sGM03g                         Provence Bakery   
5     zhxnD7J5_sCrKSw5cwI9dQ               Popeyes Louisiana Kitchen   
6     2kWrSFkIes_d2BMg4YrRtA                               Pizza Hut   
7     6llKs7K_tn8ChXcIM-oTvg                            Sansei Japan   
8     nqnYDW_FMwuTejAPNEOhqA       Seasonal Adventures Pumpkin Patch   
9     YV9GVfmDSDM7HSV0jVdTOA                           El Pollo Loco   
10    F7OsiFk9aLZtqZczA84xpw               Popeyes Louisiana Kitchen   
11    XeDLyY2a7nZ3IEY4RYslXA                 Chicago Brewing Company   
12    MDVbJicJvqaO4WGx0vEabQ                                 Chili's   
13    AAcaGYggq4RBbFdEueB2qw                    Green Valley Grocery   
14    Zh6fxrqsKqdSVmTK3roxBQ             Triumph Property Management   
15    sOkQ2Y1-D8h18oN5NgxuLg  Haddies Car Wash and Convenience store   
16    OyJDaAAMr220qkZsovCARQ                               Starbucks   
17    lv5Bnqlt93NnvNJ2oNcQ8Q                  Los Cucos Mexican Cafe   
18    D1TaFES4phv65RmsM8VCiA                          Domino's Pizza   
19    vTch8eXerkbaJbmkmYwCEw                      One Six Sky Lounge   
20    glkEaoxbewiSMBiXs945JA                             800 Degrees   
21    3TX-5V6MuGPKnZv6gW1nsg                                Cardenas   
22    lYCeqldIiOggsbByH3RRhw                             Metro Pizza   
23    tA1oBX1q6Aqj8UG3y-SqTA                                IT'SUGAR   
24    juuv0QPE_MfnVjevQTpCDg                       Manhattan Streets   
25    DbK9fyJq4O4zfT1jv6JOhw                 Pam Real Thai Las Vegas   
26    PChG1Dm0A6AXIXkXGVK8Fw                              Sasa Sushi   
27    owxcYAUca_6K6BAUX4V48w                           D'Pinoy Joint   
28    WSGHEQdcdbBWXDpna99EiQ                        Teriyaki Madness   
29    0aDCv4zPhzy7RklHDrnKQg                          Lucie's Lounge   
...                      ...                                     ...   
8778  diFj7LtBvNcgMy4Pb4_m0g   ROYCE' Las Vegas at Fashion Show Mall   
8779  6xgcHeLad-VaoTIQewK84A                         N9NE Steakhouse   
8780  _Jt9CLSL2sqF-yCNel9D-g                             Casa Robles   
8781  5FgLuegzxBvRFw5dTuETEw                             The Chelsea   
8782  dTsyfvRfN-zFdsgIDuQllQ                           Alder & Birch   
8783  OaHfq01gm8PTYkJ36k1feg     Michael T's Steaks, Ribs, & Burgers   
8784  brB2AfUTKumrRNanOZVw4w                             Scarlet Bar   
8785  ZyTrka-HiVb6Ckcl0rDaNA               Popeyes Louisiana Kitchen   
8786  vodCM302JJ_P9yJt1WuH_w                                Vege-Way   
8787  YAiHkQAQ9sm23V1CyNT2zQ                     Bogey's Bar & Grill   
8788  cYwJA2A6I12KNkm2rtXd5g                     Gordon Ramsay BurGR   
8789  RSPEJeFTKs1BsiVgjHp1WQ                  Spago by Wolfgang Puck   
8790  YhCh4mAs52COFPNLJUOFWQ                               Tonic Bar   
8791  SUTTl_NCJb5JYdlMBnuVxg                       Wetzel's Pretzels   
8792  swtA5YoSGm0V5esQuDm2NQ                                  Social   
8793  YC1FXuG7IQneHnhbHT0XcQ                           The Lobby Bar   
8794  WEPqQjRGviPyCKEmPhALSw                      The Coachman's Inn   
8795  ZVetFAAt0_j0tEqiakpecA                         Jack in the Box   
8796  WUswpeAjbiww_xkSS8jTEA          Pupusas La Familiar Restaurant   
8797  5iAFiMPfitcYDMeII5_dnQ                           Auntie Anne's   
8798  qtc1YZix_5lHBJTZq7DOpA                               Zeffirino   
8799  PDIh1lVtKlUqPJROXYJQvQ                                     FIX   
8800  TEpHybMZew9kKadvseEbEQ                             Kung Fu Tea   
8801  g62SlImzhs6_1t-knPjd8w    Red Square Restaurant & Vo

In [12]:
dat1.columns.values

array(['BusinessId', 'RestaurantName', 'Neighborhood', 'Address', 'City',
       'State', 'Zip', 'Stars', 'ReviewCount', 'AcceptsInsurance',
       'AgesAllowed', 'Alcohol', 'Ambience', 'BYOB', 'BYOBCorkage',
       'BestNights', 'BikeParking', 'BusinessAcceptsBitcoin',
       'BusinessAcceptsCreditCards', 'BusinessParking',
       'ByAppointmentOnly', 'Caters', 'CoatCheck', 'Corkage',
       'DietaryRestrictions', 'DogsAllowed', 'DriveThru', 'GoodForDancing',
       'GoodForKids', 'GoodForMeal', 'HairSpecializesIn', 'HappyHour',
       'HasTV', 'Music', 'NoiseLevel', 'Open24Hours', 'OutdoorSeating',
       'RestaurantsAttire', 'RestaurantsCounterService',
       'RestaurantsDelivery', 'RestaurantsGoodForGroups',
       'RestaurantsPriceRange2', 'RestaurantsReservations',
       'RestaurantsTableService', 'RestaurantsTakeOut', 'Smoking',
       'WheelchairAccessible', 'WiFi'], dtype=object)

In [13]:
dat1.HasTV.unique()
dat1.WheelchairAccessible.unique()
dat1.HappyHour.unique()
dat1.GoodForDancing.unique()
dat1.DriveThru.unique()
dat1.DogsAllowed.unique()
dat1.Corkage.unique()
dat1.RestaurantsReservations.unique()
dat1.RestaurantsTableService.unique()
dat1.RestaurantsTakeOut.unique()
dat1.RestaurantsCounterService.unique()
dat1.RestaurantsDelivery.unique()
dat1.RestaurantsGoodForGroups.unique()
dat1.CoatCheck.unique()
dat1.Caters.unique()
dat1.ByAppointmentOnly.unique()
dat1.BusinessAcceptsCreditCards.unique()
dat1.BusinessAcceptsBitcoin.unique()
dat1.BikeParking.unique()
dat1.BYOB.unique()
dat1.GoodForKids.unique()
dat1.Open24Hours.unique()
dat1.OutdoorSeating.unique()
dat1.AcceptsInsurance.unique()

array([ nan,   0.,   1.])

In [14]:
dat1.WiFi.unique()
#Mapping : no=0,free=1, paid=2
dat1.WiFi.replace('no',0,inplace=True)
dat1.WiFi.replace('free',1,inplace=True)
dat1.WiFi.replace('paid',2,inplace=True)
dat1.WiFi.unique()

array([ nan,   0.,   1.,   2.])

In [15]:
dat1.Smoking.unique()
#Mapping : no=0, yes=1, outdoor=2
dat1.Smoking.replace('no',0,inplace=True)
dat1.Smoking.replace('yes',1,inplace=True)
dat1.Smoking.replace('outdoor',2,inplace=True)
dat1.Smoking.unique()

array([ nan,   0.,   1.,   2.])

In [16]:
#Dont Know what they represent
dat1.RestaurantsPriceRange2.unique()

array([nan, '1', '2', '3', '4'], dtype=object)

In [17]:
dat1.RestaurantsAttire.unique()
#Mapping : casual=0, dressy=1, formal=2
dat1.RestaurantsAttire.replace('casual',0,inplace=True)
dat1.RestaurantsAttire.replace('dressy',1,inplace=True)
dat1.RestaurantsAttire.replace('formal',2,inplace=True)
dat1.RestaurantsAttire.unique()

array([ nan,   0.,   1.,   2.])

In [18]:
dat1.NoiseLevel.unique()
#Mapping : quiet=0,average=1, loud=2, very_loud=3
dat1.NoiseLevel.replace('quiet',0,inplace=True)
dat1.NoiseLevel.replace('average',1,inplace=True)
dat1.NoiseLevel.replace('loud',2,inplace=True)
dat1.NoiseLevel.replace('very_loud',3,inplace=True)
dat1.NoiseLevel.unique()

array([ nan,   1.,   2.,   0.,   3.])

In [19]:
dat1.BYOBCorkage.unique()
#Mapping : no->0, yes_free->1, yes_corkage->2
dat1.BYOBCorkage.replace('no',0,inplace=True)
dat1.BYOBCorkage.replace('yes_free',1,inplace=True)
dat1.BYOBCorkage.replace('yes_corkage',2,inplace=True)
dat1.BYOBCorkage.unique()

array([ nan,   1.,   0.,   2.])

In [20]:
#Range of Ages Allowed
dat1.AgesAllowed.unique()
#Mapping : allages->0,18plus->1,21plus->2
dat1.AgesAllowed.replace('allages',0,inplace=True)
dat1.AgesAllowed.replace('18plus',1,inplace=True)
dat1.AgesAllowed.replace('21plus',2,inplace=True)
dat1.AgesAllowed.unique()

array([ nan,   2.,   0.,   1.])

In [21]:
#Range of Alcohol
dat1.Alcohol.unique()
#Mapping : none->0, beer_and_wine->1,full_bar->2
dat1.Alcohol.replace('none',0,inplace=True)
dat1.Alcohol.replace('beer_and_wine',1,inplace=True)
dat1.Alcohol.replace('full_bar',2,inplace=True)
dat1.Alcohol.unique()

array([ nan,   0.,   1.,   2.])

In [22]:
#Mapping - count number of True Values - number of best nights in a week
for row in tqdm_notebook(dat1.BestNights):
    if type(row)==type(''):
        dat1.BestNights.replace(row,row.count('True'),inplace=True)   
dat1.BestNights.unique()

HBox(children=(IntProgress(value=0, max=8808), HTML(value='')))

array([ nan,   3.,   1.,   0.,   2.])

In [23]:
#Mapping - count number of True Values - number of types of ambiences it offers
for row in tqdm_notebook(dat1.Ambience):
    if type(row)==type(''):
        dat1.Ambience.replace(row,row.count('True'),inplace=True)   
dat1.Ambience.unique()

HBox(children=(IntProgress(value=0, max=8808), HTML(value='')))

array([ nan,   1.,   0.,   2.,   3.,   4.,   5.,   6.,   7.])

In [24]:
#Mapping - count number of True Values - number of types of parkings available
#eg- {'garage': True, 'street': False, 'validated': False, 'lot': False, 'valet': False} has 1 type of parking
# and "{'garage': True, 'street': True, 'validated': False, 'lot': False, 'valet': True}" has 3
for row in tqdm_notebook(dat1.BusinessParking):
    if type(row)==type(''):
        dat1.BusinessParking.replace(row,row.count('True'),inplace=True)   
dat1.BusinessParking.unique()

HBox(children=(IntProgress(value=0, max=8808), HTML(value='')))

array([ nan,   1.,   0.,   2.,   3.,   4.,   5.])

In [25]:
for row in tqdm_notebook(dat1.GoodForMeal):
    if type(row)==type(''):
        dat1.GoodForMeal.replace(row,row.count('True'),inplace=True)   
dat1.GoodForMeal.unique()

HBox(children=(IntProgress(value=0, max=8808), HTML(value='')))

array([ nan,   3.,   0.,   2.,   1.,   4.,   6.,   5.])

In [26]:
for row in tqdm_notebook(dat1.HairSpecializesIn):
    if type(row)==type(''):
        dat1.HairSpecializesIn.replace(row,row.count('True'),inplace=True)   
dat1.HairSpecializesIn.unique()

HBox(children=(IntProgress(value=0, max=8808), HTML(value='')))

array([ nan,   6.,   5.])

In [27]:
for row in tqdm_notebook(dat1.Music):
    if type(row)==type(''):
        dat1.Music.replace(row,row.count('True'),inplace=True)   
dat1.Music.unique()

HBox(children=(IntProgress(value=0, max=8808), HTML(value='')))

array([ nan,   0.,   1.,   2.,   3.,   4.,   5.,   6.])

In [28]:
#dat1.DietaryRestrictions.unique()
#7 types/combos of dietry restrictions. These are as follows -
dat1.DietaryRestrictions.replace("{'dairy-free': True, 'gluten-free': False, 'vegan': True, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': True}",0,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': False, 'gluten-free': False, 'vegan': False, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': True}",1,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': True, 'gluten-free': False, 'vegan': True, 'kosher': False, 'halal': False, 'soy-free': True, 'vegetarian': True}",2,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': False, 'gluten-free': False, 'vegan': True, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': True}",3,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': False, 'gluten-free': False, 'vegan': True, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': False}",4,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': True, 'gluten-free': False, 'vegan': False, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': True}",5,inplace=True)
dat1.DietaryRestrictions.replace("{'dairy-free': False, 'gluten-free': True, 'vegan': False, 'kosher': False, 'halal': False, 'soy-free': False, 'vegetarian': False}",6,inplace=True)
dat1.DietaryRestrictions.unique()

array([ nan,   0.,   1.,   2.,   3.,   4.,   5.,   6.])

In [29]:
dat1.fillna('Null', inplace=True)


In [30]:
dat1.to_csv('LasVegas_Restaurants_Temp.csv',',')